site_name: EEFA Notebook
site_description: Python scripts and Jupyter notebooks for the EEFA book
site_author: EEFA Authors
site_url: https://gee-community.github.io/eefa-notebook

repo_url: https://github.com/gee-community/eefa-notebook

theme:
  palette:
    - scheme: default
      #   primary: blue
      #   accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.highlight
  custom_dir: "docs/overrides"
  font:
    text: Google Sans
    code: Regular

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      # execute: True
      allow_errors: false
      ignore: ["name.ipynb"]
      execute_ignore: ["path/*.ipynb"]

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

# extra:
#   analytics:
#     provider: google
#     property: G-XXX

nav:
  - Home: index.md
  - Report Issues: https://github.com/gee-community/eefa-notebook/issues
