site_name: Mkdocs Template
site_description: A website template for using mkdocs
site_author: Qiusheng Wu
site_url: https://giswqs.github.io/mkdocs-template

repo_url: https://github.com/giswqs/mkdocs-template

copyright: "Copyright &copy; 2022 - 2023 Qiusheng Wu"

theme:
  palette:
    - scheme: default
      #   primary: blue
      #   accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.highlight
  custom_dir: "docs/overrides"
  font:
    text: Google Sans
    code: Regular

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      # execute: True
      allow_errors: false
      ignore: ["name.ipynb"]
      execute_ignore: "path/*.ipynb"

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

# extra:
#   analytics:
#     provider: google
#     property: G-XXX

nav:
  - Home: index.md
  - Report Issues: https://github.com/gee-community/eefa-notebook/issues
